export const smartPhonicsWordBank = {
  level1: {
    unit1: {
      targetSound: "a,b,c",
      unitTitle: "ABC",
      words: ["A", "a", "B", "b", "C", "c"],
    },
    unit2: {
      targetSound: "d,e,f",
      unitTitle: "DEF",
      words: ["D", "d", "E", "e", "F", "f"],
    },
    unit3: {
      targetSound: "g,h,i",
      unitTitle: "GHI",
      words: ["G", "g", "H", "h", "I", "i"],
    },
    unit4: {
      targetSound: "j,k,l",
      unitTitle: "JKL",
      words: ["J", "j", "K", "k", "L", "l"],
    },
    unit5: {
      targetSound: "m,n,o",
      unitTitle: "MNO",
      words: ["M", "m", "N", "n", "O", "o"],
    },
    unit6: {
      targetSound: "p,q,r",
      unitTitle: "PQR",
      words: ["P", "p", "Q", "q", "R", "r"],
    },
    unit7: {
      targetSound: "s,t,u,v",
      unitTitle: "STUV",
      words: ["S", "s", "T", "t", "U", "u", "V", "v"],
    },
    unit8: {
      targetSound: "w,x,y,z",
      unitTitle: "WXYZ",
      words: ["W", "w", "X", "x", "Y", "y", "Z", "z"],
    },
  },
  level2: {
    unit1: {
      targetSound: "a",
      unitTitle: "Short Vowel a",
      words: ["dam", "ham", "jam", "ram", "cap", "lap", "map", "nap"],
    },
    unit2: {
      targetSound: "a",
      unitTitle: "Short Vowel a",
      words: ["can", "fan", "man", "pan", "bat", "cat", "hat", "mat"],
    },
    unit3: {
      targetSound: "e",
      unitTitle: "Short Vowel e",
      words: ["jet", "net", "vet", "wet", "bed", "red", "hen", "pen"],
    },
    unit4: {
      targetSound: "i",
      unitTitle: "Short Vowel i",
      words: ["bib", "rib", "kid", "lid", "pig", "wig", "fin", "pin"],
    },
    unit5: {
      targetSound: "i",
      unitTitle: "Short Vowel i",
      words: ["dip", "hip", "lip", "rip", "hit", "sit", "mix", "six"],
    },
    unit6: {
      targetSound: "o",
      unitTitle: "Short Vowel o",
      words: ["hot", "pot", "box", "fox", "cop", "hop", "dog", "log"],
    },
    unit7: {
      targetSound: "u",
      unitTitle: "Short Vowel u",
      words: ["bug", "hug", "mug", "rug", "rub", "tub", "cup", "pup"],
    },
    unit8: {
      targetSound: "u",
      unitTitle: "Short Vowel u",
      words: ["bun", "fun", "run", "sun", "bud", "mud", "cut", "nut"],
    },
  },
  level3: {
    unit1: {
      targetSound: "a_e",
      unitTitle: "Long Vowel a",
      words: ["bake", "cake", "lake", "rake", "cape", "tape", "cave", "wave"],
    },
    unit2: {
      targetSound: "a_e",
      unitTitle: "Long Vowel a",
      words: ["game", "name", "date", "gate", "cane", "mane", "case", "vase"],
    },
    unit3: {
      targetSound: "i_e",
      unitTitle: "Long Vowel i",
      words: ["line", "nine", "pine", "vine", "bike", "hike", "lime", "time"],
    },
    unit4: {
      targetSound: "i_e",
      unitTitle: "Long Vowel i",
      words: ["hide", "ride", "pipe", "wipe", "bite", "kite", "dive", "five"],
    },
    unit5: {
      targetSound: "o_e",
      unitTitle: "Long Vowel o",
      words: ["hose", "nose", "pose", "rose", "hope", "rope", "note", "vote"],
    },
    unit6: {
      targetSound: "o_e",
      unitTitle: "Long Vowel o",
      words: ["hole", "mole", "pole", "sole", "dome", "home", "bone", "cone"],
    },
    unit7: {
      targetSound: "u_e",
      unitTitle: "Long Vowel u",
      words: ["cube", "tube", "cute", "mute", "mule", "dune", "June", "tune"],
    },
  },
  level4: {
    unit1: {
      targetSound: "bl, cl, fl",
      unitTitle: "bl, cl, fl",
      words: [
        "black",
        "blade",
        "blimp",
        "blue",
        "clam",
        "clap",
        "cliff",
        "clock",
        "flag",
        "flame",
        "flap",
        "flute",
      ],
    },
    unit2: {
      targetSound: "br, cr, fr",
      unitTitle: "br, cr, fr",
      words: [
        "brake",
        "brave",
        "brick",
        "bride",
        "crab",
        "crane",
        "crib",
        "cross",
        "frame",
        "frog",
        "front",
        "frost",
      ],
    },
    unit3: {
      targetSound: "gl, pl, sl",
      unitTitle: "gl, pl, sl",
      words: [
        "glass",
        "globe",
        "glove",
        "glue",
        "plane",
        "plant",
        "plate",
        "plum",
        "sled",
        "slice",
        "slide",
        "slim",
      ],
    },
    unit4: {
      targetSound: "dr, pr, tr",
      unitTitle: "dr, pr, tr",
      words: [
        "dragon",
        "dress",
        "drive",
        "drum",
        "press",
        "price",
        "print",
        "prize",
        "trace",
        "track",
        "truck",
        "trumpet",
      ],
    },
    unit5: {
      targetSound: "sm, sn, st, sw",
      unitTitle: "sm, sn, st, sw",
      words: [
        "smell",
        "smile",
        "smoke",
        "snack",
        "snake",
        "snore",
        "stone",
        "stop",
        "stove",
        "sweet",
        "swim",
        "swing",
      ],
    },
    unit6: {
      targetSound: "ng, nk",
      unitTitle: "ng, nk",
      words: [
        "bang",
        "fang",
        "king",
        "ring",
        "gong",
        "song",
        "bank",
        "tank",
        "pink",
        "wink",
        "dunk",
        "junk",
      ],
    },
    unit7: {
      targetSound: "sh, ch",
      unitTitle: "sh, ch",
      words: [
        "shape",
        "ship",
        "shop",
        "brush",
        "fish",
        "flash",
        "cherry",
        "chick",
        "chin",
        "bench",
        "branch",
        "catch",
      ],
    },
    unit8: {
      targetSound: "th, wh",
      unitTitle: "th, wh",
      words: [
        "thick",
        "thin",
        "thumb",
        "bath",
        "math",
        "teeth",
        "whale",
        "wheel",
        "whip",
        "whisk",
        "whisper",
        "white",
      ],
    },
  },
  level5: {
    unit1: {
      targetSound: "ee, ea",
      unitTitle: "ee, ea",
      words: [
        "bee",
        "feet",
        "green",
        "peel",
        "seed",
        "tree",
        "leaf",
        "meat",
        "peanut",
        "sea",
        "seal",
        "tea",
      ],
    },
    unit2: {
      targetSound: "oa, ow",
      unitTitle: "oa, ow",
      words: [
        "boat",
        "coat",
        "goat",
        "road",
        "soap",
        "toast",
        "blow",
        "bowl",
        "pillow",
        "snow",
        "window",
        "yellow",
      ],
    },
    unit3: {
      targetSound: "ai, ay",
      unitTitle: "ai, ay",
      words: [
        "mail",
        "nail",
        "rail",
        "rain",
        "tail",
        "train",
        "clay",
        "gray",
        "hay",
        "play",
        "pray",
        "tray",
      ],
    },
    unit4: {
      targetSound: "oi, oy",
      unitTitle: "oi, oy",
      words: [
        "boil",
        "coil",
        "coin",
        "foil",
        "oil",
        "point",
        "soil",
        "toilet",
        "boy",
        "joy",
        "soybean",
        "toy",
      ],
    },
    unit5: {
      targetSound: "ow, ou",
      unitTitle: "ow, ou",
      words: [
        "brown",
        "clown",
        "cow",
        "crown",
        "gown",
        "owl",
        "blouse",
        "cloud",
        "count",
        "house",
        "mouse",
        "mouth",
      ],
    },
    unit6: {
      targetSound: "ir, er, ur",
      unitTitle: "ir, er, ur",
      words: [
        "bird",
        "girl",
        "shirt",
        "skirt",
        "letter",
        "singer",
        "soccer",
        "teacher",
        "nurse",
        "purple",
        "purse",
        "turtle",
      ],
    },
    unit7: {
      targetSound: "ar, or",
      unitTitle: "ar, or",
      words: [
        "arm",
        "car",
        "card",
        "farmer",
        "park",
        "star",
        "cork",
        "corn",
        "fork",
        "horse",
        "north",
        "store",
      ],
    },
    unit8: {
      targetSound: "oo",
      unitTitle: "oo",
      words: [
        "book",
        "cook",
        "foot",
        "hook",
        "look",
        "wood",
        "food",
        "goose",
        "moon",
        "pool",
        "spoon",
        "zoo",
      ],
    },
  },
}

export const englishVoices = [
  {
    name: "Aria",
    voice_id: "9BWtsMINqrJLrRacOk9x",
    gender: "FEMALE",
    description:
      "A middle-aged female with an African-American accent. Calm with a hint of rasp.",
    use_case: "INFORMATIVE_EDUCATIONAL",
  },
  {
    name: "Laura",
    voice_id: "FGY2WhTYpPnrIDTdsKH5",
    gender: "FEMALE",
    description:
      "This young adult female voice delivers sunny enthusiasm with a quirky attitude.",
    use_case: "SOCIAL_MEDIA",
  },
  {
    name: "River",
    voice_id: "SAz9YHcvj6GT2YYXdXww",
    gender: "NEUTRAL",
    description:
      "A relaxed, neutral voice ready for narrations or conversational projects.",
    use_case: "CONVERSATIONAL",
  },
  {
    name: "Liam",
    voice_id: "TX3LPaxmHKxFdv7VOQHJ",
    gender: "MALE",
    description:
      "A young adult with energy and warmth - suitable for reels and shorts.",
    use_case: "SOCIAL_MEDIA",
  },
  {
    name: "Matilda",
    voice_id: "XrExE9yKIg1WjnnlVkGX",
    gender: "FEMALE",
    description:
      "A professional woman with a pleasing alto pitch. Suitable for many use cases.",
    use_case: "INFORMATIVE_EDUCATIONAL",
  },
  {
    name: "Will",
    voice_id: "bIHbv24MWmeRgasZH58o",
    gender: "MALE",
    description: "Conversational and laid back.",
    use_case: "CONVERSATIONAL",
  },
  {
    name: "Jessica",
    voice_id: "cgSgspJ2msm6clMCkdW9",
    gender: "FEMALE",
    description:
      "Young and popular, this playful American female voice is perfect for trendy content.",
    use_case: "CONVERSATIONAL",
  },
  // {
  //   name: "Eric",
  //   voice_id: "cjVigY5qzO86Huf0OWal",
  //   gender: "MALE",
  //   description:
  //     "A smooth tenor pitch from a man in his 40s - perfect for agentic use cases.",
  //   use_case: "CONVERSATIONAL",
  // },
  {
    name: "Chris",
    voice_id: "iP95p4xoKVk53GoZ742B",
    gender: "MALE",
    description:
      "Natural and real, this down-to-earth voice is great across many use-cases.",
    use_case: "CONVERSATIONAL",
  },
  {
    name: "Brian",
    voice_id: "nPczCjzI2devNBz1zQrb",
    gender: "MALE",
    description:
      "Middle-aged man with a resonant and comforting tone. Great for narrations and advertisements.",
    use_case: "SOCIAL_MEDIA",
  },
  {
    name: "Bill",
    voice_id: "pqHfZKP75CvOlQylNhV4",
    gender: "MALE",
    description: "Friendly and comforting voice ready to narrate your stories.",
    use_case: "ADVERTISEMENT",
  },
]

export const playerSymbols = ["X", "O", "△", "□", "☆"]
