export const smartPhonicsWordBank = {
  level1: {
    unit1: { targetSound: "a,b,c", words: ["A", "a", "B", "b", "C", "c"] },
    unit2: { targetSound: "d,e,f", words: ["D", "d", "E", "e", "F", "f"] },
    unit3: { targetSound: "g,h,i", words: ["G", "g", "H", "h", "I", "i"] },
    unit4: { targetSound: "j,k,l", words: ["J", "j", "K", "k", "L", "l"] },
    unit5: { targetSound: "m,n,o", words: ["M", "m", "N", "n", "O", "o"] },
    unit6: { targetSound: "p,q,r", words: ["P", "p", "Q", "q", "R", "r"] },
    unit7: {
      targetSound: "s,t,u,v",
      words: ["S", "s", "T", "t", "U", "u", "V", "v"],
    },
    unit8: {
      targetSound: "w,x,y,z",
      words: ["W", "w", "X", "x", "Y", "y", "Z", "z"],
    },
  },
  level2: {
    unit1: {
      targetSound: "a",
      words: ["dam", "ham", "jam", "ram", "cap", "lap", "map", "nap"],
    },
    unit2: {
      targetSound: "a",
      words: ["can", "fan", "man", "pan", "bat", "cat", "hat", "mat"],
    },
    unit3: {
      targetSound: "e",
      words: ["jet", "net", "vet", "wet", "bed", "red", "hen", "pen"],
    },
    unit4: {
      targetSound: "i",
      words: ["bib", "rib", "kid", "lid", "pig", "wig", "fin", "pin"],
    },
    unit5: {
      targetSound: "i",
      words: ["dip", "hip", "lip", "rip", "hit", "sit", "mix", "six"],
    },
    unit6: {
      targetSound: "o",
      words: ["hot", "pot", "box", "fox", "cop", "hop", "dog", "log"],
    },
    unit7: {
      targetSound: "u",
      words: ["bug", "hug", "mug", "rug", "rub", "tub", "cup", "pup"],
    },
    unit8: {
      targetSound: "u",
      words: ["bun", "fun", "run", "sun", "bud", "mud", "cut", "nut"],
    },
  },
  level3: {
    unit1: {
      targetSound: "a_e",
      words: ["bake", "cake", "lake", "rake", "cape", "tape", "cave", "wave"],
    },
    unit2: {
      targetSound: "a_e",
      words: ["game", "name", "date", "gate", "cane", "mane", "case", "vase"],
    },
    unit3: {
      targetSound: "i_e",
      words: ["line", "nine", "pine", "vine", "bike", "hike", "lime", "time"],
    },
    unit4: {
      targetSound: "i_e",
      words: ["hide", "ride", "pipe", "wipe", "bite", "kite", "dive", "five"],
    },
    unit5: {
      targetSound: "o_e",
      words: ["hose", "nose", "pose", "rose", "hope", "rope", "note", "vote"],
    },
    unit6: {
      targetSound: "o_e",
      words: ["hole", "mole", "pole", "sole", "dome", "home", "bone", "cone"],
    },
    unit7: {
      targetSound: "u_e",
      words: ["cube", "tube", "cute", "mute", "mule", "dune", "June", "tune"],
    },
  },
  level4: {
    unit1: {
      targetSound: "bl, cl, fl",
      words: [
        "black",
        "blade",
        "blimp",
        "blue",
        "clam",
        "clap",
        "cliff",
        "clock",
        "flag",
        "flame",
        "flap",
        "flute",
      ],
    },
    unit2: {
      targetSound: "br, cr, fr",
      words: [
        "brake",
        "brave",
        "brick",
        "bride",
        "crab",
        "crane",
        "crib",
        "cross",
        "frame",
        "frog",
        "front",
        "frost",
      ],
    },
    unit3: {
      targetSound: "gl, pl, sl",
      words: [
        "glass",
        "globe",
        "glove",
        "glue",
        "plane",
        "plant",
        "plate",
        "plum",
        "sled",
        "slice",
        "slide",
        "slim",
      ],
    },
    unit4: {
      targetSound: "dr, pr, tr",
      words: [
        "dragon",
        "dress",
        "drive",
        "drum",
        "press",
        "price",
        "print",
        "prize",
        "trace",
        "track",
        "truck",
        "trumpet",
      ],
    },
    unit5: {
      targetSound: "sm, sn, st, sw",
      words: [
        "smell",
        "smile",
        "smoke",
        "snack",
        "snake",
        "snore",
        "stone",
        "stop",
        "stove",
        "sweet",
        "swim",
        "swing",
      ],
    },
    unit6: {
      targetSound: "ng, nk",
      words: [
        "bang",
        "fang",
        "king",
        "ring",
        "gong",
        "song",
        "bank",
        "tank",
        "pink",
        "wink",
        "dunk",
        "junk",
      ],
    },
    unit7: {
      targetSound: "sh, ch",
      words: [
        "shape",
        "ship",
        "shop",
        "brush",
        "fish",
        "flash",
        "cherry",
        "chick",
        "chin",
        "bench",
        "branch",
        "catch",
      ],
    },
    unit8: {
      targetSound: "th, wh",
      words: [
        "thick",
        "thin",
        "thumb",
        "bath",
        "math",
        "teeth",
        "whale",
        "wheel",
        "whip",
        "whisk",
        "whisper",
        "white",
      ],
    },
  },
  level5: {
    unit1: {
      targetSound: "ee, ea",
      words: [
        "bee",
        "feet",
        "green",
        "peel",
        "seed",
        "tree",
        "leaf",
        "meat",
        "peanut",
        "sea",
        "seal",
        "tea",
      ],
    },
    unit2: {
      targetSound: "oa, ow",
      words: [
        "boat",
        "coat",
        "goat",
        "road",
        "soap",
        "toast",
        "blow",
        "bowl",
        "pillow",
        "snow",
        "window",
        "yellow",
      ],
    },
    unit3: {
      targetSound: "ai, ay",
      words: [
        "mail",
        "nail",
        "rail",
        "rain",
        "tail",
        "train",
        "clay",
        "gray",
        "hay",
        "play",
        "pray",
        "tray",
      ],
    },
    unit4: {
      targetSound: "oi, oy",
      words: [
        "boil",
        "coil",
        "coin",
        "foil",
        "oil",
        "point",
        "soil",
        "toilet",
        "boy",
        "joy",
        "soybean",
        "toy",
      ],
    },
    unit5: {
      targetSound: "ow, ou",
      words: [
        "brown",
        "clown",
        "cow",
        "crown",
        "gown",
        "owl",
        "blouse",
        "cloud",
        "count",
        "house",
        "mouse",
        "mouth",
      ],
    },
    unit6: {
      targetSound: "ir, er, ur",
      words: [
        "bird",
        "girl",
        "shirt",
        "skirt",
        "letter",
        "singer",
        "soccer",
        "teacher",
        "nurse",
        "purple",
        "purse",
        "turtle",
      ],
    },
    unit7: {
      targetSound: "ar, or",
      words: [
        "arm",
        "car",
        "card",
        "farmer",
        "park",
        "star",
        "cork",
        "corn",
        "fork",
        "horse",
        "north",
        "store",
      ],
    },
    unit8: {
      targetSound: "oo",
      words: [
        "book",
        "cook",
        "foot",
        "hook",
        "look",
        "wood",
        "food",
        "goose",
        "moon",
        "pool",
        "spoon",
        "zoo",
      ],
    },
  },
}

export const MATCH_LENGTH = 3
export const playerSymbols = ["X", "O", "△", "□", "☆"]
export const COLOR_PALETTE = [
  "var(--orange-7)",
  "var(--pink-7)",
  "var(--green-7)",
  "var(--blue-7)",
  "var(--violet-7)",
  "var(--cyan-7)",
  "var(--red-7)",
]
